### PR TITLE
🐛 Fix includeCommentBlock

### PR DESCRIPTION
**Pull request by markbrouch**
This fixes a bug where calling `renderAsYAML` with `includeCommentBlock = true` causes only the comment block to be rendered, and not the rest of the yaml object.

### CODE REVIEW

**Comment by sinshutu** [comment]
@richseviora When will this PR be merged?

**Review by richseviora — APPROVED** [review]

**Comment by richseviora** [comment]
I had totally missed this! Thank you @markbrouch for the PR and @sinshutu for the reminder! I'm publishing a new version shortly.

**Comment by richseviora** [comment]
And it's published! Thanks again :)

**Comment by sinshutu** [comment]
Thank you @richseviora @markbrouch

**Pull request merged**
